# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[framework]
simple_name = "numba"
full_name = "Numba"
prefix = "nb"
class = "NumbaFramework"
arch = "cpu"

[[framework.postfixes]]
impl_postfix = "numba_n"
description = "Numba nopython"

[[framework.postfixes]]
impl_postfix = "numba_np"
description = "Numba nopython, Parallel=True"

[[framework.postfixes]]
impl_postfix = "numba_npr"
description = "Numba nopython, Parallel=True, prange"
