# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "LU Decomposition"
short_name = "ludcmp"
relative_path = "ludcmp"
module_name = "ludcmp"
func_name = "kernel"
kind = "microbench"
domain = "Solver"
dwarf = "dense_linear_algebra"
input_args = [
    "A",
    "b",
]
array_args = [
    "A",
    "b",
]
output_args = [
    "A",
]

[benchmark.parameters.S]
N = 60

[benchmark.parameters.M]
N = 220

[benchmark.parameters.L]
N = 650

[benchmark.parameters.paper]
N = 2000

[benchmark.init]
func_name = "initialize"
input_args = [
    "N",
]
output_args = [
    "A",
    "b",
]
